Fix for python libraries on Linux Mint
The instructions [here](Running duckyPad Configurator on Linux) do not appear to work for my Linux Mint PC.

I wanted to post how I was able to fix this. So that maybe we can update the documentation.

Let me know your thoughts. It seemed that whenever I tried to execute the python script (duckypad_config.py) I got the following:

sudo python3 duckypad_config.py
Traceback (most recent call last):
  File "duckypad_config.py", line 13, in <module>
    from tkinter import *
ModuleNotFoundError: No module named *'tkinter'*

Once I installed tk, I would then get the error for *appdirs* then for *hid*